package Cliente;

import Partida.FileManager;
import static Partida.MenuPrincipal.infoBox;
import java.awt.Color;
import java.awt.Image;
import java.io.IOException;
import java.io.Serializable;
import java.net.Socket;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

// Interfaz grafica que le aparece a cada jugador, el diseno es un placeholder porque ocupamos poner el tablero y el historial (yo hago el historial)

public class InterfazCliente extends javax.swing.JFrame implements Serializable{

    public Cliente refCliente;
    private String nombreTurno = "";            // Nombre del jugador cuyo turno es actualmente
    private String nombreJugador = "";          // Nombre del jugador
    /**
     * Creates new form ChatCliente
     */
    public InterfazCliente() {
        initComponents();
       // lblDado1.setOpaque(true);
       // lblDado2.setOpaque(true);
    }

    public Cliente getRefCliente() {
        return refCliente;
    }

    public JPanel getPnlTablero() {
        return pnlTablero;
    }

    public void setPnlTablero(JPanel pnlTablero) {
        this.pnlTablero = pnlTablero;
    }

    public JLabel getLblNombreJugador() {
        return lblNombreJugador;
    }

    public JPanel getLblGo() {
        return lblImpuestos1;
    }

    public void setLblGo(JPanel lblGo) {
        this.lblImpuestos1 = lblGo;
    }

    public JPanel getLblElMuelle4() {
        return lblElMuelle4;
    }

    public void setLblElMuelle4(JPanel lblElMuelle4) {
        this.lblElMuelle4 = lblElMuelle4;
    }

    
    
    public JPanel getLblElMuelle() {
        return lblElMuelle;
    }

    public void setLblElMuelle(JPanel lblElMuelle) {
        this.lblElMuelle = lblElMuelle;
    }
    
   
    
    public JPanel getPnlToolbar() {
        return pnlToolbar;
    }

    public void setPnlToolbar(JPanel pnlToolbar) {
        this.pnlToolbar = pnlToolbar;
    }

    
    
    public void setLblNombreJugador(JLabel lblNombreJugador) {
        this.lblNombreJugador = lblNombreJugador;
    }

    

    public void setRefCliente(Cliente refCliente) {
        this.refCliente = refCliente;
    }

    public void setNombreTurno(String nombreTurno) {
        this.nombreTurno = nombreTurno;
        lblTurno.setText(nombreTurno);
    }

    public void setNombreJugador(String nombreJugador){
        this.nombreJugador = nombreJugador;
        lblNombreJugador.setText(nombreJugador);
    }

    public String getNombreJugador() {
        return nombreJugador;
    }
    
    
    
    public void addMensaje(String msj)              // Para agregar un mensaje en la interfaz del cliente
    {
        txaMensajes.append(msj + "\n");
    }    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTurno = new javax.swing.JLabel();
        lblUsuarioLanzamiento = new javax.swing.JLabel();
        lblHistorial = new javax.swing.JLabel();
        lblChat = new javax.swing.JLabel();
        txfMensaje = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        lblTurnoDe = new javax.swing.JLabel();
        lblNombreJugador = new javax.swing.JLabel();
        lblFicha = new javax.swing.JLabel();
        lblNumDinero = new javax.swing.JLabel();
        lblStatusPartida = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaHistorial = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaMensajes = new javax.swing.JTextArea();
        lblDinero = new javax.swing.JLabel();
        pnlFicha = new javax.swing.JPanel();
        lblFichaJugador = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pnlTablero = new javax.swing.JPanel();
        jPanel110 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jPanel70 = new javax.swing.JPanel();
        lblGo1 = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        lblImpuestos1 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        lblElMuelle1 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        jPanel72 = new javax.swing.JPanel();
        lblElMuelle2 = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        lblElMuelle3 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        lblElMuelle4 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jPanel77 = new javax.swing.JPanel();
        lblElMuelle = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        lblElMuelle5 = new javax.swing.JPanel();
        jLabel64 = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        jPanel36 = new javax.swing.JPanel();
        lblElMuelle7 = new javax.swing.JPanel();
        jLabel70 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        lblElMuelle8 = new javax.swing.JPanel();
        jLabel71 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        lblElMuelle9 = new javax.swing.JPanel();
        jLabel72 = new javax.swing.JLabel();
        lblElMuelle10 = new javax.swing.JPanel();
        jLabel73 = new javax.swing.JLabel();
        jPanel53 = new javax.swing.JPanel();
        lblElMuelle11 = new javax.swing.JPanel();
        jLabel74 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        lblElMuelle12 = new javax.swing.JPanel();
        jLabel75 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblElMuelle13 = new javax.swing.JPanel();
        jLabel76 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jPanel46 = new javax.swing.JPanel();
        lblElMuelle14 = new javax.swing.JPanel();
        jLabel77 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        lblElMuelle15 = new javax.swing.JPanel();
        jLabel78 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        lblElMuelle16 = new javax.swing.JPanel();
        jLabel79 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        lblElMuelle17 = new javax.swing.JPanel();
        jLabel80 = new javax.swing.JLabel();
        lblElMuelle18 = new javax.swing.JPanel();
        jLabel81 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        lblElMuelle19 = new javax.swing.JPanel();
        jLabel86 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel131 = new javax.swing.JLabel();
        lblElMuelle20 = new javax.swing.JPanel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jPanel54 = new javax.swing.JPanel();
        lblElMuelle21 = new javax.swing.JPanel();
        jLabel93 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jPanel57 = new javax.swing.JPanel();
        lblElMuelle22 = new javax.swing.JPanel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jPanel116 = new javax.swing.JPanel();
        lblElMuelle23 = new javax.swing.JPanel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        lblElMuelle24 = new javax.swing.JPanel();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jPanel113 = new javax.swing.JPanel();
        lblElMuelle25 = new javax.swing.JPanel();
        jLabel105 = new javax.swing.JLabel();
        jPanel118 = new javax.swing.JPanel();
        jPanel109 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        lblElMuelle26 = new javax.swing.JPanel();
        jLabel107 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        lblElMuelle27 = new javax.swing.JPanel();
        jLabel109 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        lblElMuelle28 = new javax.swing.JPanel();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        lblElMuelle29 = new javax.swing.JPanel();
        jLabel113 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        lblElMuelle30 = new javax.swing.JPanel();
        jLabel115 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        lblElMuelle32 = new javax.swing.JPanel();
        jLabel119 = new javax.swing.JLabel();
        jLabel120 = new javax.swing.JLabel();
        jPanel34 = new javax.swing.JPanel();
        lblElMuelle33 = new javax.swing.JPanel();
        jLabel121 = new javax.swing.JLabel();
        jLabel122 = new javax.swing.JLabel();
        lblElMuelle34 = new javax.swing.JPanel();
        jLabel106 = new javax.swing.JLabel();
        jLabel123 = new javax.swing.JLabel();
        jLabel132 = new javax.swing.JLabel();
        lblElMuelle35 = new javax.swing.JPanel();
        jLabel124 = new javax.swing.JLabel();
        jLabel125 = new javax.swing.JLabel();
        lblElMuelle36 = new javax.swing.JPanel();
        jLabel126 = new javax.swing.JLabel();
        jLabel127 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lblElMuelle37 = new javax.swing.JPanel();
        jLabel128 = new javax.swing.JLabel();
        jLabel129 = new javax.swing.JLabel();
        lblElMuelle38 = new javax.swing.JPanel();
        jLabel130 = new javax.swing.JLabel();
        jLabel133 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        pnlToolbar = new javax.swing.JPanel();
        btnVenderProp = new javax.swing.JButton();
        btnComprarPropActual = new javax.swing.JButton();
        btnLanzarDados = new javax.swing.JButton();
        btnHipotecar = new javax.swing.JButton();
        btnEndTurn = new javax.swing.JButton();
        lblSeleccionFicha = new javax.swing.JLabel();
        cbSeleccion = new javax.swing.JComboBox<>();
        btnSeleccionFicha = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblDado1 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lblDado2 = new javax.swing.JLabel();
        cbPropiedades = new javax.swing.JComboBox<>();
        lblAdministrar = new javax.swing.JLabel();
        btnCompraCasa = new javax.swing.JButton();
        btnVenderEdificio = new javax.swing.JButton();
        cbEdificios = new javax.swing.JComboBox<>();
        lblVenderEdificio = new javax.swing.JLabel();
        btnCompraHotel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTurno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTurno.setText("nadie");
        jPanel1.add(lblTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 90, 40));
        jPanel1.add(lblUsuarioLanzamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 735, -1, 68));

        lblHistorial.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHistorial.setText("Historial");
        jPanel1.add(lblHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, -1, -1));

        lblChat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblChat.setText("Chat comunal");
        jPanel1.add(lblChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 680, -1, -1));
        jPanel1.add(txfMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 890, 310, 70));

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 890, 70, 70));

        lblTurnoDe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTurnoDe.setText("Es turno de:");
        jPanel1.add(lblTurnoDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        lblNombreJugador.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNombreJugador.setText("Sin nombre...");
        jPanel1.add(lblNombreJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 140, 40));

        lblFicha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFicha.setText("Ficha:");
        jPanel1.add(lblFicha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 70, -1));

        lblNumDinero.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNumDinero.setText("0 $");
        jPanel1.add(lblNumDinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 120, 29));

        lblStatusPartida.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblStatusPartida.setText("Esperando para iniciar...");
        jPanel1.add(lblStatusPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 160, 30));

        lblLogo.setIcon(new ImageIcon("src/Imagenes/logo.png"));
        jPanel1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 400, 130));

        txaHistorial.setColumns(20);
        txaHistorial.setRows(5);
        jScrollPane2.setViewportView(txaHistorial);

        jScrollPane3.setViewportView(jScrollPane2);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 380, 230));

        txaMensajes.setColumns(20);
        txaMensajes.setRows(5);
        jScrollPane1.setViewportView(txaMensajes);

        jScrollPane4.setViewportView(jScrollPane1);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 710, 380, 180));

        lblDinero.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDinero.setText("Dinero:");
        jPanel1.add(lblDinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        javax.swing.GroupLayout pnlFichaLayout = new javax.swing.GroupLayout(pnlFicha);
        pnlFicha.setLayout(pnlFichaLayout);
        pnlFichaLayout.setHorizontalGroup(
            pnlFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFichaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblFichaJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlFichaLayout.setVerticalGroup(
            pnlFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFichaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblFichaJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(pnlFicha, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 0, 400, 1000));

        jPanel2.setLayout(new javax.swing.OverlayLayout(jPanel2));

        pnlTablero.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        pnlTablero.setLayout(null);

        jPanel110.setBackground(new java.awt.Color(255, 255, 255));
        jPanel110.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel43.setText("ARCA COMUNAL");

        javax.swing.GroupLayout jPanel110Layout = new javax.swing.GroupLayout(jPanel110);
        jPanel110.setLayout(jPanel110Layout);
        jPanel110Layout.setHorizontalGroup(
            jPanel110Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel43, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel110Layout.setVerticalGroup(
            jPanel110Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel110Layout.createSequentialGroup()
                .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlTablero.add(jPanel110);
        jPanel110.setBounds(10, 180, 170, 50);

        jPanel70.setBackground(new java.awt.Color(0, 0, 153));
        jPanel70.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel70Layout = new javax.swing.GroupLayout(jPanel70);
        jPanel70.setLayout(jPanel70Layout);
        jPanel70Layout.setHorizontalGroup(
            jPanel70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel70Layout.setVerticalGroup(
            jPanel70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        pnlTablero.add(jPanel70);
        jPanel70.setBounds(1230, 530, 20, 60);

        lblGo1.setBackground(new java.awt.Color(255, 255, 255));
        lblGo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblGo1.setLayout(new javax.swing.OverlayLayout(lblGo1));

        jLabel59.setText("GO (COBRE 200$)");
        jLabel59.setAlignmentY(0.2F);
        lblGo1.add(jLabel59);

        pnlTablero.add(lblGo1);
        lblGo1.setBounds(1229, 588, 140, 70);

        lblImpuestos1.setBackground(new java.awt.Color(255, 255, 255));
        lblImpuestos1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImpuestos1.setLayout(new javax.swing.OverlayLayout(lblImpuestos1));

        jLabel47.setText("IMPUESTOS ($100)");
        jLabel47.setAlignmentX(0.5F);
        lblImpuestos1.add(jLabel47);

        pnlTablero.add(lblImpuestos1);
        lblImpuestos1.setBounds(1228, 470, 140, 60);

        lblElMuelle1.setBackground(new java.awt.Color(255, 255, 255));
        lblElMuelle1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblElMuelle1.setLayout(new javax.swing.OverlayLayout(lblElMuelle1));

        jLabel60.setText("PLAZA PARK $350");
        lblElMuelle1.add(jLabel60);

        pnlTablero.add(lblElMuelle1);
        lblElMuelle1.setBounds(1250, 400, 118, 70);

        jPanel72.setBackground(new java.awt.Color(0, 0, 153));
        jPanel72.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel72Layout = new javax.swing.GroupLayout(jPanel72);
        jPanel72.setLayout(jPanel72Layout);
        jPanel72Layout.setHorizontalGroup(
            jPanel72Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel72Layout.setVerticalGroup(
            jPanel72Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        pnlTablero.add(jPanel72);
        jPanel72.setBounds(1230, 400, 20, 70);

        lblElMuelle2.setBackground(new java.awt.Color(255, 255, 255));
        lblElMuelle2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblElMuelle2.setLayout(new javax.swing.OverlayLayout(lblElMuelle2));

        jLabel61.setText("FORTUNA");
        jLabel61.setAlignmentX(0.5F);
        lblElMuelle2.add(jLabel61);

        pnlTablero.add(lblElMuelle2);
        lblElMuelle2.setBounds(1228, 340, 140, 60);

        lblElMuelle3.setBackground(new java.awt.Color(255, 255, 255));
        lblElMuelle3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblElMuelle3.setLayout(new javax.swing.OverlayLayout(lblElMuelle3));

        jLabel62.setText("FERROCARRIL");
        jLabel62.setAlignmentY(1.0F);
        lblElMuelle3.add(jLabel62);

        jLabel82.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel82.setText("$200");
        jLabel82.setAlignmentX(0.1F);
        jLabel82.setAlignmentY(0.1F);
        lblElMuelle3.add(jLabel82);

        pnlTablero.add(lblElMuelle3);
        lblElMuelle3.setBounds(1228, 280, 140, 60);

        lblElMuelle4.setBackground(new java.awt.Color(255, 255, 255));
        lblElMuelle4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblElMuelle4.setLayout(new javax.swing.OverlayLayout(lblElMuelle4));

        jLabel63.setText("AV. PENSILVANIA");
        jLabel63.setAlignmentY(1.0F);
        lblElMuelle4.add(jLabel63);

        jLabel83.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel83.setText("$320");
        jLabel83.setAlignmentX(0.1F);
        jLabel83.setAlignmentY(0.1F);
        lblElMuelle4.add(jLabel83);

        pnlTablero.add(lblElMuelle4);
        lblElMuelle4.setBounds(1250, 220, 118, 60);

        jPanel77.setBackground(new java.awt.Color(0, 153, 0));
        jPanel77.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel77Layout = new javax.swing.GroupLayout(jPanel77);
        jPanel77.setLayout(jPanel77Layout);
        jPanel77Layout.setHorizontalGroup(
            jPanel77Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel77Layout.setVerticalGroup(
            jPanel77Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        pnlTablero.add(jPanel77);
        jPanel77.setBounds(1230, 220, 20, 60);

        lblElMuelle.setBackground(new java.awt.Color(255, 255, 255));
        lblElMuelle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblElMuelle.setLayout(new javax.swing.OverlayLayout(lblElMuelle));

        jLabel58.setText("ARCA COMUNAL");
        lblElMuelle.add(jLabel58);

        pnlTablero.add(lblElMuelle);
        lblElMuelle.setBounds(1228, 170, 140, 50);

        lblElMuelle5.setBackground(new java.awt.Color(255, 255, 255));
        lblElMuelle5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblElMuelle5.setLayout(new javax.swing.OverlayLayout(lblElMuelle5));

        jLabel64.setText("VAYA A LA CÁRCEL");
        jLabel64.setAlignmentY(0.3F);
        lblElMuelle5.add(jLabel64);

        pnlTablero.add(lblElMuelle5);
        lblElMuelle5.setBounds(1248, 0, 120, 60);

        jPanel38.setBackground(new java.awt.Color(0, 153, 0));
        jPanel38.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel38Layout = new javax.swing.GroupLayout(jPanel38);
        jPanel38.setLayout(jPanel38Layout);
        jPanel38Layout.setHorizontalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel38Layout.setVerticalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        pnlTablero.add(jPanel38);
        jPanel38.setBounds(1230, 110, 20, 60);

        jPanel36.setBackground(new java.awt.Color(0, 153, 0));
        jPanel36.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        pnlTablero.add(jPanel36);
        jPanel36.setBounds(1230, 60, 20, 50);

        lblElMuelle7.setBackground(new java.awt.Color(255, 255, 255));
        lblElMuelle7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblElMuelle7.setLayout(new javax.swing.OverlayLayout(lblElMuelle7));

        jLabel70.setText("JARDINES MARVIN");
        jLabel70.setAlignmentY(1.0F);
        lblElMuelle7.add(jLabel70);

        jLabel84.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel84.setText("$280");
        jLabel84.setAlignmentX(0.1F);
        jLabel84.setAlignmentY(0.1F);
        lblElMuelle7.add(jLabel84);

        pnlTablero.add(lblElMuelle7);
        lblElMuelle7.setBounds(1130, 0, 118, 50);

        lblElMuelle8.setBackground(new java.awt.Color(255, 255, 255));
        lblElMuelle8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblElMuelle8.setLayout(new javax.swing.OverlayLayout(lblElMuelle8));

        jLabel71.setText("AV. PACÍFICO");
        jLabel71.setAlignmentY(1.0F);
        lblElMuelle8.add(jLabel71);

        jLabel85.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel85.setText("$300");
        jLabel85.setAlignmentX(0.1F);
        jLabel85.setAlignmentY(0.1F);
        lblElMuelle8.add(jLabel85);

        pnlTablero.add(lblElMuelle8);
        lblElMuelle8.setBounds(1250, 60, 118, 60);

        lblElMuelle9.setBackground(new java.awt.Color(255, 255, 255));
        lblElMuelle9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblElMuelle9.setLayout(new javax.swing.OverlayLayout(lblElMuelle9));

        jLabel72.setText("EL MUELLE ($400)");
        jLabel72.setAlignmentX(0.2F);
        lblElMuelle9.add(jLabel72);

        pnlTablero.add(lblElMuelle9);
        lblElMuelle9.setBounds(1248, 530, 120, 60);

        lblElMuelle10.setBackground(new java.awt.Color(255, 255, 255));
        lblElMuelle10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblElMuelle10.setLayout(new javax.swing.OverlayLayout(lblElMuelle10));

        jLabel73.setText("FORTUNA");
        jLabel73.setAlignmentX(0.5F);
        jLabel73.setAlignmentY(0.0F);
        lblElMuelle10.add(jLabel73);

        pnlTablero.add(lblElMuelle10);
        lblElMuelle10.setBounds(290, 0, 120, 60);

        jPanel53.setBackground(new java.awt.Color(255, 255, 0));
        jPanel53.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel53Layout = new javax.swing.GroupLayout(jPanel53);
        jPanel53.setLayout(jPanel53Layout);
        jPanel53Layout.setHorizontalGroup(
            jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel53Layout.setVerticalGroup(
            jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        pnlTablero.add(jPanel53);
        jPanel53.setBounds(1130, 50, 120, 10);

        lblElMuelle11.setBackground(new java.awt.Color(255, 255, 255));
        lblElMuelle11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblElMuelle11.setLayout(new javax.swing.OverlayLayout(lblElMuelle11));

        jLabel74.setText("AV. N. CAROLINA");
        jLabel74.setAlignmentY(1.0F);
        lblElMuelle11.add(jLabel74);

        jLabel87.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel87.setText("$320");
        jLabel87.setAlignmentX(0.1F);
        jLabel87.setAlignmentY(0.1F);
        lblElMuelle11.add(jLabel87);

        pnlTablero.add(lblElMuelle11);
        lblElMuelle11.setBounds(1250, 110, 118, 60);

        lblElMuelle12.setBackground(new java.awt.Color(255, 255, 255));
        lblElMuelle12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblElMuelle12.setLayout(new javax.swing.OverlayLayout(lblElMuelle12));

        jLabel75.setText("AGUA");
        jLabel75.setAlignmentY(1.0F);
        lblElMuelle12.add(jLabel75);

        jLabel88.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel88.setText("$150");
        jLabel88.setAlignmentX(0.1F);
        jLabel88.setAlignmentY(0.1F);
        lblElMuelle12.add(jLabel88);

        pnlTablero.add(lblElMuelle12);
        lblElMuelle12.setBounds(1028, 0, 110, 60);

        jPanel5.setBackground(new java.awt.Color(255, 255, 0));
        jPanel5.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        pnlTablero.add(jPanel5);
        jPanel5.setBounds(910, 50, 120, 10);

        lblElMuelle13.setBackground(new java.awt.Color(255, 255, 255));
        lblElMuelle13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblElMuelle13.setLayout(new javax.swing.OverlayLayout(lblElMuelle13));

        jLabel76.setText("AVENIDA VENTNOR");
        jLabel76.setAlignmentY(1.0F);
        lblElMuelle13.add(jLabel76);

        jLabel89.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel89.setText("$260");
        jLabel89.setAlignmentX(0.1F);
        jLabel89.setAlignmentY(0.1F);
        lblElMuelle13.add(jLabel89);

        pnlTablero.add(lblElMuelle13);
        lblElMuelle13.setBounds(910, 0, 120, 50);

        jPanel46.setBackground(new java.awt.Color(255, 255, 0));
        jPanel46.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel46Layout = new javax.swing.GroupLayout(jPanel46);
        jPanel46.setLayout(jPanel46Layout);
        jPanel46Layout.setHorizontalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel46Layout.setVerticalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        pnlTablero.add(jPanel46);
        jPanel46.setBounds(780, 50, 130, 10);

        lblElMuelle14.setBackground(new java.awt.Color(255, 255, 255));
        lblElMuelle14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblElMuelle14.setLayout(new javax.swing.OverlayLayout(lblElMuelle14));

        jLabel77.setText("AV. ATLÁNTICO");
        jLabel77.setAlignmentY(1.0F);
        lblElMuelle14.add(jLabel77);

        jLabel90.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel90.setText("$260");
        jLabel90.setAlignmentX(0.1F);
        jLabel90.setAlignmentY(0.1F);
        lblElMuelle14.add(jLabel90);

        pnlTablero.add(lblElMuelle14);
        lblElMuelle14.setBounds(780, 0, 130, 50);

        jPanel28.setBackground(new java.awt.Color(255, 0, 0));
        jPanel28.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        pnlTablero.add(jPanel28);
        jPanel28.setBounds(410, 50, 120, 10);

        lblElMuelle15.setBackground(new java.awt.Color(255, 255, 255));
        lblElMuelle15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblElMuelle15.setLayout(new javax.swing.OverlayLayout(lblElMuelle15));

        jLabel78.setText("FERROCARRIL B&O");
        jLabel78.setAlignmentY(1.0F);
        lblElMuelle15.add(jLabel78);

        jLabel91.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel91.setText("$200");
        jLabel91.setAlignmentX(0.1F);
        jLabel91.setAlignmentY(0.1F);
        lblElMuelle15.add(jLabel91);

        pnlTablero.add(lblElMuelle15);
        lblElMuelle15.setBounds(650, 0, 130, 60);

        lblElMuelle16.setBackground(new java.awt.Color(255, 255, 255));
        lblElMuelle16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblElMuelle16.setLayout(new javax.swing.OverlayLayout(lblElMuelle16));

        jLabel79.setText("AVENIDA  ILLINOIS");
        jLabel79.setAlignmentY(1.0F);
        lblElMuelle16.add(jLabel79);

        jLabel92.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel92.setText("$240");
        jLabel92.setAlignmentX(0.1F);
        jLabel92.setAlignmentY(0.1F);
        lblElMuelle16.add(jLabel92);

        pnlTablero.add(lblElMuelle16);
        lblElMuelle16.setBounds(530, 0, 120, 50);

        jPanel31.setBackground(new java.awt.Color(255, 0, 0));
        jPanel31.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        pnlTablero.add(jPanel31);
        jPanel31.setBounds(530, 40, 120, 20);

        lblElMuelle17.setBackground(new java.awt.Color(255, 255, 255));
        lblElMuelle17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblElMuelle17.setLayout(new javax.swing.OverlayLayout(lblElMuelle17));

        jLabel80.setText("PARQUEO LIBRE");
        jLabel80.setAlignmentX(0.5F);
        jLabel80.setAlignmentY(0.0F);
        lblElMuelle17.add(jLabel80);

        pnlTablero.add(lblElMuelle17);
        lblElMuelle17.setBounds(10, 0, 150, 60);

        lblElMuelle18.setBackground(new java.awt.Color(255, 255, 255));
        lblElMuelle18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblElMuelle18.setLayout(new javax.swing.OverlayLayout(lblElMuelle18));

        jLabel81.setText("AVENIDA INDIANA");
        jLabel81.setAlignmentY(1.0F);
        lblElMuelle18.add(jLabel81);

        jLabel94.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel94.setText("$220");
        jLabel94.setAlignmentX(0.1F);
        jLabel94.setAlignmentY(0.1F);
        lblElMuelle18.add(jLabel94);

        pnlTablero.add(lblElMuelle18);
        lblElMuelle18.setBounds(410, 0, 120, 50);

        jPanel18.setBackground(new java.awt.Color(255, 0, 0));
        jPanel18.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        pnlTablero.add(jPanel18);
        jPanel18.setBounds(160, 50, 130, 10);

        lblElMuelle19.setBackground(new java.awt.Color(255, 255, 255));
        lblElMuelle19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblElMuelle19.setLayout(new javax.swing.OverlayLayout(lblElMuelle19));

        jLabel86.setText("FERROCARRIL");
        jLabel86.setAlignmentX(1.0F);
        jLabel86.setAlignmentY(1.0F);
        lblElMuelle19.add(jLabel86);

        jLabel95.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel95.setText("READING");
        jLabel95.setAlignmentX(1.0F);
        jLabel95.setAlignmentY(0.0F);
        lblElMuelle19.add(jLabel95);

        jLabel131.setText("    $200");
        jLabel131.setAlignmentY(1.0F);
        lblElMuelle19.add(jLabel131);

        pnlTablero.add(lblElMuelle19);
        lblElMuelle19.setBounds(680, 590, 140, 70);

        lblElMuelle20.setBackground(new java.awt.Color(255, 255, 255));
        lblElMuelle20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblElMuelle20.setLayout(new javax.swing.OverlayLayout(lblElMuelle20));

        jLabel96.setText("AVENIDA KENTUCKY");
        jLabel96.setAlignmentY(1.0F);
        lblElMuelle20.add(jLabel96);

        jLabel97.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel97.setText("$220");
        jLabel97.setAlignmentX(0.1F);
        jLabel97.setAlignmentY(0.1F);
        lblElMuelle20.add(jLabel97);

        pnlTablero.add(lblElMuelle20);
        lblElMuelle20.setBounds(160, 0, 130, 50);

        jPanel54.setBackground(new java.awt.Color(255, 102, 0));
        jPanel54.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel54Layout = new javax.swing.GroupLayout(jPanel54);
        jPanel54.setLayout(jPanel54Layout);
        jPanel54Layout.setHorizontalGroup(
            jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel54Layout.setVerticalGroup(
            jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        pnlTablero.add(jPanel54);
        jPanel54.setBounds(160, 60, 20, 60);

        lblElMuelle21.setBackground(new java.awt.Color(255, 255, 255));
        lblElMuelle21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblElMuelle21.setLayout(new javax.swing.OverlayLayout(lblElMuelle21));

        jLabel93.setText("AV. NUEVA YORK");
        jLabel93.setAlignmentY(1.0F);
        lblElMuelle21.add(jLabel93);

        jLabel98.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel98.setText("$200");
        jLabel98.setAlignmentX(0.1F);
        jLabel98.setAlignmentY(0.1F);
        lblElMuelle21.add(jLabel98);

        pnlTablero.add(lblElMuelle21);
        lblElMuelle21.setBounds(10, 60, 150, 60);

        jPanel57.setBackground(new java.awt.Color(255, 102, 0));
        jPanel57.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel57Layout = new javax.swing.GroupLayout(jPanel57);
        jPanel57.setLayout(jPanel57Layout);
        jPanel57Layout.setHorizontalGroup(
            jPanel57Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel57Layout.setVerticalGroup(
            jPanel57Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        pnlTablero.add(jPanel57);
        jPanel57.setBounds(160, 120, 20, 60);

        lblElMuelle22.setBackground(new java.awt.Color(255, 255, 255));
        lblElMuelle22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblElMuelle22.setLayout(new javax.swing.OverlayLayout(lblElMuelle22));

        jLabel99.setText("AVENIDA TENNESSEE");
        jLabel99.setAlignmentY(1.0F);
        lblElMuelle22.add(jLabel99);

        jLabel100.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel100.setText("$180");
        jLabel100.setAlignmentX(0.1F);
        jLabel100.setAlignmentY(0.1F);
        lblElMuelle22.add(jLabel100);

        pnlTablero.add(lblElMuelle22);
        lblElMuelle22.setBounds(10, 120, 150, 60);

        jPanel116.setBackground(new java.awt.Color(255, 102, 0));
        jPanel116.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel116Layout = new javax.swing.GroupLayout(jPanel116);
        jPanel116.setLayout(jPanel116Layout);
        jPanel116Layout.setHorizontalGroup(
            jPanel116Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel116Layout.setVerticalGroup(
            jPanel116Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        pnlTablero.add(jPanel116);
        jPanel116.setBounds(160, 230, 20, 60);

        lblElMuelle23.setBackground(new java.awt.Color(255, 255, 255));
        lblElMuelle23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblElMuelle23.setLayout(new javax.swing.OverlayLayout(lblElMuelle23));

        jLabel101.setText("ELECTRICIDAD");
        jLabel101.setAlignmentY(1.0F);
        lblElMuelle23.add(jLabel101);

        jLabel102.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel102.setText("$150");
        jLabel102.setAlignmentX(0.1F);
        jLabel102.setAlignmentY(0.1F);
        lblElMuelle23.add(jLabel102);

        pnlTablero.add(lblElMuelle23);
        lblElMuelle23.setBounds(10, 460, 170, 60);

        lblElMuelle24.setBackground(new java.awt.Color(255, 255, 255));
        lblElMuelle24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblElMuelle24.setLayout(new javax.swing.OverlayLayout(lblElMuelle24));

        jLabel103.setText("AVENIDA ST. JAMES");
        jLabel103.setAlignmentY(1.0F);
        lblElMuelle24.add(jLabel103);

        jLabel104.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel104.setText("$180");
        jLabel104.setAlignmentX(0.1F);
        jLabel104.setAlignmentY(0.1F);
        lblElMuelle24.add(jLabel104);

        pnlTablero.add(lblElMuelle24);
        lblElMuelle24.setBounds(10, 230, 150, 60);

        jPanel113.setBackground(new java.awt.Color(255, 0, 153));
        jPanel113.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel113Layout = new javax.swing.GroupLayout(jPanel113);
        jPanel113.setLayout(jPanel113Layout);
        jPanel113Layout.setHorizontalGroup(
            jPanel113Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel113Layout.setVerticalGroup(
            jPanel113Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        pnlTablero.add(jPanel113);
        jPanel113.setBounds(160, 340, 20, 60);

        lblElMuelle25.setBackground(new java.awt.Color(255, 255, 255));
        lblElMuelle25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblElMuelle25.setLayout(new javax.swing.OverlayLayout(lblElMuelle25));

        jLabel105.setText("FORTUNA");
        jLabel105.setAlignmentX(0.5F);
        jLabel105.setAlignmentY(0.0F);
        lblElMuelle25.add(jLabel105);

        pnlTablero.add(lblElMuelle25);
        lblElMuelle25.setBounds(440, 590, 120, 70);

        jPanel118.setBackground(new java.awt.Color(255, 0, 153));
        jPanel118.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel118Layout = new javax.swing.GroupLayout(jPanel118);
        jPanel118.setLayout(jPanel118Layout);
        jPanel118Layout.setHorizontalGroup(
            jPanel118Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel118Layout.setVerticalGroup(
            jPanel118Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        pnlTablero.add(jPanel118);
        jPanel118.setBounds(160, 400, 20, 60);

        jPanel109.setBackground(new java.awt.Color(255, 0, 153));
        jPanel109.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel109Layout = new javax.swing.GroupLayout(jPanel109);
        jPanel109.setLayout(jPanel109Layout);
        jPanel109Layout.setHorizontalGroup(
            jPanel109Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel109Layout.setVerticalGroup(
            jPanel109Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        pnlTablero.add(jPanel109);
        jPanel109.setBounds(160, 520, 20, 70);

        jPanel24.setBackground(new java.awt.Color(0, 153, 153));
        jPanel24.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        pnlTablero.add(jPanel24);
        jPanel24.setBounds(160, 590, 150, 10);

        jPanel7.setBackground(new java.awt.Color(0, 153, 153));
        jPanel7.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        pnlTablero.add(jPanel7);
        jPanel7.setBounds(305, 590, 140, 10);

        lblElMuelle26.setBackground(new java.awt.Color(255, 255, 255));
        lblElMuelle26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblElMuelle26.setLayout(new javax.swing.OverlayLayout(lblElMuelle26));

        jLabel107.setText("AVENIDA CONNECTICUT");
        jLabel107.setAlignmentY(1.0F);
        lblElMuelle26.add(jLabel107);

        jLabel108.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel108.setText("$120");
        jLabel108.setAlignmentX(0.1F);
        jLabel108.setAlignmentY(0.1F);
        lblElMuelle26.add(jLabel108);

        pnlTablero.add(lblElMuelle26);
        lblElMuelle26.setBounds(160, 590, 150, 70);

        lblElMuelle27.setBackground(new java.awt.Color(255, 255, 255));
        lblElMuelle27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblElMuelle27.setLayout(new javax.swing.OverlayLayout(lblElMuelle27));

        jLabel109.setText("AVENIDA STATUS");
        jLabel109.setAlignmentY(1.0F);
        lblElMuelle27.add(jLabel109);

        jLabel110.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel110.setText("$140");
        jLabel110.setAlignmentX(0.1F);
        jLabel110.setAlignmentY(0.1F);
        lblElMuelle27.add(jLabel110);

        pnlTablero.add(lblElMuelle27);
        lblElMuelle27.setBounds(10, 400, 150, 60);

        lblElMuelle28.setBackground(new java.awt.Color(255, 255, 255));
        lblElMuelle28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblElMuelle28.setLayout(new javax.swing.OverlayLayout(lblElMuelle28));

        jLabel111.setText("PLAZA SAN CARLOS");
        jLabel111.setAlignmentY(1.0F);
        lblElMuelle28.add(jLabel111);

        jLabel112.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel112.setText("$140");
        jLabel112.setAlignmentX(0.1F);
        jLabel112.setAlignmentY(0.1F);
        lblElMuelle28.add(jLabel112);

        pnlTablero.add(lblElMuelle28);
        lblElMuelle28.setBounds(10, 520, 150, 70);

        lblElMuelle29.setBackground(new java.awt.Color(255, 255, 255));
        lblElMuelle29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblElMuelle29.setLayout(new javax.swing.OverlayLayout(lblElMuelle29));

        jLabel113.setText("LA CÁRCEL");
        jLabel113.setAlignmentY(1.0F);
        lblElMuelle29.add(jLabel113);

        jLabel114.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel114.setText("$140");
        jLabel114.setAlignmentX(0.1F);
        jLabel114.setAlignmentY(0.1F);
        lblElMuelle29.add(jLabel114);

        pnlTablero.add(lblElMuelle29);
        lblElMuelle29.setBounds(10, 590, 150, 70);

        lblElMuelle30.setBackground(new java.awt.Color(255, 255, 255));
        lblElMuelle30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblElMuelle30.setLayout(new javax.swing.OverlayLayout(lblElMuelle30));

        jLabel115.setText("AVENIDA VIRGINIA");
        jLabel115.setAlignmentY(1.0F);
        lblElMuelle30.add(jLabel115);

        jLabel116.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel116.setText("$160");
        jLabel116.setAlignmentX(0.1F);
        jLabel116.setAlignmentY(0.1F);
        lblElMuelle30.add(jLabel116);

        pnlTablero.add(lblElMuelle30);
        lblElMuelle30.setBounds(10, 340, 150, 60);

        lblElMuelle32.setBackground(new java.awt.Color(255, 255, 255));
        lblElMuelle32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblElMuelle32.setLayout(new javax.swing.OverlayLayout(lblElMuelle32));

        jLabel119.setText("AVENIDA VERMONT");
        jLabel119.setAlignmentY(1.0F);
        lblElMuelle32.add(jLabel119);

        jLabel120.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel120.setText("$100");
        jLabel120.setAlignmentX(0.1F);
        jLabel120.setAlignmentY(0.1F);
        lblElMuelle32.add(jLabel120);

        pnlTablero.add(lblElMuelle32);
        lblElMuelle32.setBounds(310, 600, 130, 60);

        jPanel34.setBackground(new java.awt.Color(0, 153, 153));
        jPanel34.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        pnlTablero.add(jPanel34);
        jPanel34.setBounds(560, 590, 120, 10);

        lblElMuelle33.setBackground(new java.awt.Color(255, 255, 255));
        lblElMuelle33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblElMuelle33.setLayout(new javax.swing.OverlayLayout(lblElMuelle33));

        jLabel121.setText("ARCA");
        jLabel121.setAlignmentY(1.0F);
        lblElMuelle33.add(jLabel121);

        jLabel122.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel122.setText("COMUNAL");
        jLabel122.setAlignmentX(0.1F);
        jLabel122.setAlignmentY(0.1F);
        lblElMuelle33.add(jLabel122);

        pnlTablero.add(lblElMuelle33);
        lblElMuelle33.setBounds(1010, 590, 90, 70);

        lblElMuelle34.setBackground(new java.awt.Color(255, 255, 255));
        lblElMuelle34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblElMuelle34.setLayout(new javax.swing.OverlayLayout(lblElMuelle34));

        jLabel106.setText("FERROCARRIL");
        jLabel106.setAlignmentX(1.0F);
        jLabel106.setAlignmentY(1.0F);
        lblElMuelle34.add(jLabel106);

        jLabel123.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel123.setText("PENSILVANIA");
        jLabel123.setAlignmentX(1.0F);
        jLabel123.setAlignmentY(0.0F);
        lblElMuelle34.add(jLabel123);

        jLabel132.setText("    $200");
        jLabel132.setAlignmentY(1.0F);
        lblElMuelle34.add(jLabel132);

        pnlTablero.add(lblElMuelle34);
        lblElMuelle34.setBounds(10, 290, 170, 50);

        lblElMuelle35.setBackground(new java.awt.Color(255, 255, 255));
        lblElMuelle35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblElMuelle35.setLayout(new javax.swing.OverlayLayout(lblElMuelle35));

        jLabel124.setText("AVENIDA BÁLTICA");
        jLabel124.setAlignmentY(1.0F);
        lblElMuelle35.add(jLabel124);

        jLabel125.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel125.setText("$60");
        jLabel125.setAlignmentX(0.1F);
        jLabel125.setAlignmentY(0.1F);
        lblElMuelle35.add(jLabel125);

        pnlTablero.add(lblElMuelle35);
        lblElMuelle35.setBounds(900, 600, 110, 60);

        lblElMuelle36.setBackground(new java.awt.Color(255, 255, 255));
        lblElMuelle36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblElMuelle36.setLayout(new javax.swing.OverlayLayout(lblElMuelle36));

        jLabel126.setText("AV. ORIENTAL");
        jLabel126.setAlignmentY(1.0F);
        lblElMuelle36.add(jLabel126);

        jLabel127.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel127.setText("$100");
        jLabel127.setAlignmentX(0.1F);
        jLabel127.setAlignmentY(0.1F);
        lblElMuelle36.add(jLabel127);

        pnlTablero.add(lblElMuelle36);
        lblElMuelle36.setBounds(560, 600, 120, 60);

        jPanel9.setBackground(new java.awt.Color(102, 102, 0));
        jPanel9.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        pnlTablero.add(jPanel9);
        jPanel9.setBounds(900, 590, 108, 10);

        lblElMuelle37.setBackground(new java.awt.Color(255, 255, 255));
        lblElMuelle37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblElMuelle37.setLayout(new javax.swing.OverlayLayout(lblElMuelle37));

        jLabel128.setText("IMPUESTOS");
        jLabel128.setAlignmentY(1.0F);
        lblElMuelle37.add(jLabel128);

        jLabel129.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel129.setText("$260");
        jLabel129.setAlignmentX(0.1F);
        jLabel129.setAlignmentY(0.1F);
        lblElMuelle37.add(jLabel129);

        pnlTablero.add(lblElMuelle37);
        lblElMuelle37.setBounds(820, 590, 80, 70);

        lblElMuelle38.setBackground(new java.awt.Color(255, 255, 255));
        lblElMuelle38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblElMuelle38.setLayout(new javax.swing.OverlayLayout(lblElMuelle38));

        jLabel130.setText("AV. MEDITERRÁNEO");
        jLabel130.setAlignmentY(1.0F);
        lblElMuelle38.add(jLabel130);

        jLabel133.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel133.setText("$60");
        jLabel133.setAlignmentX(0.1F);
        jLabel133.setAlignmentY(0.1F);
        lblElMuelle38.add(jLabel133);

        pnlTablero.add(lblElMuelle38);
        lblElMuelle38.setBounds(1100, 600, 130, 60);

        jPanel11.setBackground(new java.awt.Color(102, 102, 0));
        jPanel11.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        pnlTablero.add(jPanel11);
        jPanel11.setBounds(1100, 590, 130, 10);

        jPanel2.add(pnlTablero);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1380, 660));

        pnlToolbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVenderProp.setText("Vender");
        pnlToolbar.add(btnVenderProp, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 90, 70));

        btnComprarPropActual.setText("Comprar propiedad actual");
        pnlToolbar.add(btnComprarPropActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 200, 70));

        btnLanzarDados.setText("Lanzar Dados");
        btnLanzarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanzarDadosActionPerformed(evt);
            }
        });
        pnlToolbar.add(btnLanzarDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 150, 70));

        btnHipotecar.setText("Hipotecar/deshipotecar");
        pnlToolbar.add(btnHipotecar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 170, 70));

        btnEndTurn.setText("Terminar turno");
        btnEndTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEndTurnActionPerformed(evt);
            }
        });
        pnlToolbar.add(btnEndTurn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 200, 130, 70));

        lblSeleccionFicha.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblSeleccionFicha.setText("Seleccionar ficha:");
        pnlToolbar.add(lblSeleccionFicha, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 170, -1));

        cbSeleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chikorita", "Slowbro", "Charizard", "Pikachu", "Yamper", "Rayquaza", "Suicune", "Entei", "Raikoui", "Mewtwo", "Espeon", "Ditto", "Cyndaquil", "Totodile" }));
        pnlToolbar.add(cbSeleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 40, 230, 30));

        btnSeleccionFicha.setText("Ficha seleccionada");
        btnSeleccionFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionFichaActionPerformed(evt);
            }
        });
        pnlToolbar.add(btnSeleccionFicha, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 20, 160, 70));

        lblDado1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblDado1.setForeground(new java.awt.Color(255, 0, 51));
        lblDado1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDado1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblDado1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlToolbar.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 120, -1));

        lblDado2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblDado2.setForeground(new java.awt.Color(255, 0, 0));
        lblDado2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDado2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDado2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        pnlToolbar.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        pnlToolbar.add(cbPropiedades, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 360, 30));

        lblAdministrar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblAdministrar.setText("Administrar propiedades:");
        pnlToolbar.add(lblAdministrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 130, 240, -1));

        btnCompraCasa.setText("Comprar casa");
        pnlToolbar.add(btnCompraCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, -1, 70));

        btnVenderEdificio.setText("Vender");
        pnlToolbar.add(btnVenderEdificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 200, 90, 70));

        pnlToolbar.add(cbEdificios, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 160, 190, 30));

        lblVenderEdificio.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblVenderEdificio.setText("Vender edificios:");
        pnlToolbar.add(lblVenderEdificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 130, -1, -1));

        btnCompraHotel.setText("Comprar hotel");
        pnlToolbar.add(btnCompraHotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, 120, 70));

        getContentPane().add(pnlToolbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 1380, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JPanel getPnlFicha() {
        return pnlFicha;
    }

    public void setPnlFicha(JPanel pnlFicha) {
        this.pnlFicha = pnlFicha;
    }

    public JLabel getLblFichaJugador() {
        return lblFichaJugador;
    }

    public void setLblFichaJugador(JLabel lblFichaJugador) {
        this.lblFichaJugador = lblFichaJugador;
    }

    public JLabel getLblDado1() {
        return lblDado1;
    }

    public void setLblDado1(JLabel lblDado1) {
        this.lblDado1 = lblDado1;
    }

    public JLabel getLblDado2() {
        return lblDado2;
    }

    public void setLblDado2(JLabel lblDado2) {
        this.lblDado2 = lblDado2;
    }

    public JPanel getLblGo1() {
        return lblGo1;
    }

    public void setLblGo1(JPanel lblGo1) {
        this.lblGo1 = lblGo1;
    }
    
    
    
    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        
        try {
            // TODO add your handling code here:
            refCliente.hiloCliente.writer.writeInt(2);      // Se envia al servidor la accion de enviar un mensaje por chat y se envia el mensaje
            refCliente.hiloCliente.writer.writeUTF(this.getLblNombreJugador().getText());
            refCliente.hiloCliente.writer.writeUTF(txfMensaje.getText());
        } catch (IOException ex) {

        }
        this.getTxfMensaje().setText("");
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnLanzarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanzarDadosActionPerformed

        if (this.getRefCliente().getHiloCliente().isTurnoConseguido()){
            try {
                this.getRefCliente().getHiloCliente().writer.writeInt(9);
                this.getRefCliente().getHiloCliente().writer.writeUTF(this.getLblNombreJugador().getText());
            } catch (IOException ex) {
                Logger.getLogger(InterfazCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
        else if (!this.getRefCliente().getHiloCliente().isTurnoConseguido()){
            Random random = new Random();
        int dado1 = random.nextInt(6); // se hace pasar de 0-5 a 1-6 sumandole 1 al resultado
        dado1 = dado1 + 1;
        this.getLblDado1().setText(""+dado1);
        
        int dado2 = random.nextInt(6); // se hace pasar de 0-5 a 1-6 sumandole 1 al resultado
        dado2 = dado2 + 1;
        this.getLblDado2().setText(""+dado2);
        
        int dadoTotal = dado1+dado2;
        
        System.out.println(dadoTotal);
        ArrayList<Integer> listaDados = (ArrayList<Integer>)FileManager.readObject("src/Partida/listadados.dat");
        if (listaDados.contains(dadoTotal)){
            this.getTxaHistorial().append(this.getLblNombreJugador().getText() + ", su resultado de dado es repetido. Por favor lance los dados de nuevo.\n");
            return;
        }
        this.getRefCliente().getHiloCliente().setTotalRoll(dadoTotal);
        listaDados.add(dadoTotal);
        System.out.println(listaDados);
        FileManager.writeObject(listaDados, "src/Partida/listadados.dat");
        ArrayList<String> listaNombres = (ArrayList<String>)FileManager.readObject("src/Partida/listanombres.dat");
        listaNombres.add(this.getRefCliente().getHiloCliente().getNombre());
        FileManager.writeObject(listaNombres, "src/Partida/listanombres.dat");
        this.getRefCliente().getHiloCliente().setTurnoConseguido(true);
        try {
            this.getRefCliente().getHiloCliente().getWriter().writeInt(3);
        } catch (IOException ex) {
            Logger.getLogger(InterfazCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
        
    }//GEN-LAST:event_btnLanzarDadosActionPerformed

    private void btnSeleccionFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionFichaActionPerformed
        // TODO add your handling code here:
        String seleccion = this.cbSeleccion.getSelectedItem().toString();
        System.out.println(seleccion);
        ArrayList<Ficha> listaFichas = (ArrayList<Ficha>)FileManager.readObject("src/Partida/listafichas.dat");
        
        if (seleccion.equals("Chikorita")){
            
            Ficha newFicha = new Ficha("Chikorita", "src/Imagenes/chikorita.png", this.getLblNombreJugador().getText());
            this.getRefCliente().getHiloCliente().setFicha(newFicha);
            JLabel newLabel = new JLabel("");
            newLabel.setVisible(true);
            //this.getLblGo().add(newLabel);
            newFicha.setLabelFicha(newLabel);
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(newFicha.getImagen()).getImage().getScaledInstance(70, 70, Image.SCALE_DEFAULT));
            newFicha.getLabelFicha().setIcon((imageIcon));
            System.out.println(newFicha.getLabelFicha().getIcon());
            newFicha.getLabelFicha().setVisible(true);
            listaFichas.add(newFicha);
            FileManager.writeObject(listaFichas, "src/Partida/listafichas.dat");
            try {
                this.getRefCliente().getHiloCliente().getWriter().writeInt(6);
            } catch (IOException ex) {
                Logger.getLogger(InterfazCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.getLblFichaJugador().setIcon(imageIcon);
        }
        
        else if (seleccion.equals("Slowbro")){
            
            Ficha newFicha = new Ficha("Slowbro", "src/Imagenes/slowbro.png", this.getLblNombreJugador().getText());
            this.getRefCliente().getHiloCliente().setFicha(newFicha);
            JLabel newLabel = new JLabel("");
            newLabel.setVisible(true);
            //this.getLblGo().add(newLabel);
            newFicha.setLabelFicha(newLabel);
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(newFicha.getImagen()).getImage().getScaledInstance(70, 70, Image.SCALE_DEFAULT));
            newFicha.getLabelFicha().setIcon((imageIcon));
            System.out.println(newFicha.getLabelFicha().getIcon());
            newFicha.getLabelFicha().setVisible(true);
            listaFichas.add(newFicha);
            FileManager.writeObject(listaFichas, "src/Partida/listafichas.dat");
            try {
                this.getRefCliente().getHiloCliente().getWriter().writeInt(6);
            } catch (IOException ex) {
                Logger.getLogger(InterfazCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.getLblFichaJugador().setIcon(imageIcon);
        }
        
        else if (seleccion.equals("Charizard")){
            
            Ficha newFicha = new Ficha("Charizard", "src/Imagenes/charizard.png", this.getLblNombreJugador().getText());
            this.getRefCliente().getHiloCliente().setFicha(newFicha);
            JLabel newLabel = new JLabel("");
            newLabel.setVisible(true);
            
            newFicha.setLabelFicha(newLabel);
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(newFicha.getImagen()).getImage().getScaledInstance(70, 70, Image.SCALE_DEFAULT));
            newFicha.getLabelFicha().setIcon((imageIcon));

            newFicha.getLabelFicha().setVisible(true);

            //this.getLblGo().add(newFicha.getLabelFicha());
            listaFichas.add(newFicha);
            FileManager.writeObject(listaFichas, "src/Partida/listafichas.dat");
            FileManager.writeObject(newFicha.getLabelFicha(), "src/Partida/prueba.dat");
            try {
                this.getRefCliente().getHiloCliente().getWriter().writeInt(6);
            } catch (IOException ex) {
                Logger.getLogger(InterfazCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.getLblFichaJugador().setIcon(imageIcon);
        }
        
        else if (seleccion.equals("Pikachu")){
            
            Ficha newFicha = new Ficha("Pikachu", "src/Imagenes/pikachu.png", this.getLblNombreJugador().getText());
            this.getRefCliente().getHiloCliente().setFicha(newFicha);
            JLabel newLabel = new JLabel("");
            newLabel.setVisible(true);
            //this.getLblGo().add(newLabel);
            newFicha.setLabelFicha(newLabel);
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(newFicha.getImagen()).getImage().getScaledInstance(70, 70, Image.SCALE_DEFAULT));
            newFicha.getLabelFicha().setIcon((imageIcon));
            System.out.println(newFicha.getLabelFicha().getIcon());
            newFicha.getLabelFicha().setVisible(true);
            listaFichas.add(newFicha);
            FileManager.writeObject(listaFichas, "src/Partida/listafichas.dat");
            try {
                this.getRefCliente().getHiloCliente().getWriter().writeInt(6);
            } catch (IOException ex) {
                Logger.getLogger(InterfazCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.getLblFichaJugador().setIcon(imageIcon);
        }
        
        else if (seleccion.equals("Yamper")){
            
            Ficha newFicha = new Ficha("Yamper", "src/Imagenes/yamper.png", this.getLblNombreJugador().getText());
            this.getRefCliente().getHiloCliente().setFicha(newFicha);
            JLabel newLabel = new JLabel("");
            newLabel.setVisible(true);
            //this.getLblGo().add(newLabel);
            newFicha.setLabelFicha(newLabel);
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(newFicha.getImagen()).getImage().getScaledInstance(70, 70, Image.SCALE_DEFAULT));
            newFicha.getLabelFicha().setIcon((imageIcon));
            System.out.println(newFicha.getLabelFicha().getIcon());
            newFicha.getLabelFicha().setVisible(true);
            listaFichas.add(newFicha);
            FileManager.writeObject(listaFichas, "src/Partida/listafichas.dat");
            try {
                this.getRefCliente().getHiloCliente().getWriter().writeInt(6);
            } catch (IOException ex) {
                Logger.getLogger(InterfazCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.getLblFichaJugador().setIcon(imageIcon);
        }
        
        else if (seleccion.equals("Rayquaza")){
            
            Ficha newFicha = new Ficha("Rayquaza", "src/Imagenes/rayquaza.png", this.getLblNombreJugador().getText());
            this.getRefCliente().getHiloCliente().setFicha(newFicha);
            JLabel newLabel = new JLabel("");
            newLabel.setVisible(true);
            //this.getLblGo().add(newLabel);
            newFicha.setLabelFicha(newLabel);
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(newFicha.getImagen()).getImage().getScaledInstance(70, 70, Image.SCALE_DEFAULT));
            newFicha.getLabelFicha().setIcon((imageIcon));
            System.out.println(newFicha.getLabelFicha().getIcon());
            newFicha.getLabelFicha().setVisible(true);
            listaFichas.add(newFicha);
            FileManager.writeObject(listaFichas, "src/Partida/listafichas.dat");
            try {
                this.getRefCliente().getHiloCliente().getWriter().writeInt(6);
            } catch (IOException ex) {
                Logger.getLogger(InterfazCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.getLblFichaJugador().setIcon(imageIcon);
        }
        
        else if (seleccion.equals("Suicune")){
            
            Ficha newFicha = new Ficha("Suicune", "src/Imagenes/suicune.png", this.getLblNombreJugador().getText());
            this.getRefCliente().getHiloCliente().setFicha(newFicha);
            JLabel newLabel = new JLabel("");
            newLabel.setVisible(true);
            //this.getLblGo().add(newLabel);
            newFicha.setLabelFicha(newLabel);
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(newFicha.getImagen()).getImage().getScaledInstance(70, 70, Image.SCALE_DEFAULT));
            newFicha.getLabelFicha().setIcon((imageIcon));
            System.out.println(newFicha.getLabelFicha().getIcon());
            newFicha.getLabelFicha().setVisible(true);
            listaFichas.add(newFicha);
            FileManager.writeObject(listaFichas, "src/Partida/listafichas.dat");
            try {
                this.getRefCliente().getHiloCliente().getWriter().writeInt(6);
            } catch (IOException ex) {
                Logger.getLogger(InterfazCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.getLblFichaJugador().setIcon(imageIcon);
        }
        
        else if (seleccion.equals("Entei")){
            
            Ficha newFicha = new Ficha("Entei", "src/Imagenes/entei.png", this.getLblNombreJugador().getText());
            this.getRefCliente().getHiloCliente().setFicha(newFicha);
            JLabel newLabel = new JLabel("");
            newLabel.setVisible(true);
            newFicha.setLabelFicha(newLabel);
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(newFicha.getImagen()).getImage().getScaledInstance(70, 70, Image.SCALE_DEFAULT));
            newFicha.getLabelFicha().setIcon((imageIcon));
            newFicha.getLabelFicha().setVisible(true);
            listaFichas.add(newFicha);
            FileManager.writeObject(listaFichas, "src/Partida/listafichas.dat");
            try {
                this.getRefCliente().getHiloCliente().getWriter().writeInt(6);
            } catch (IOException ex) {
                Logger.getLogger(InterfazCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.getLblFichaJugador().setIcon(imageIcon);
        }
        
        else if (seleccion.equals("Raikou")){
            
            Ficha newFicha = new Ficha("Raikou", "src/Imagenes/raikou.png", this.getLblNombreJugador().getText());
            this.getRefCliente().getHiloCliente().setFicha(newFicha);
            JLabel newLabel = new JLabel("");
            newLabel.setVisible(true);
            //this.getLblGo().add(newLabel);
            newFicha.setLabelFicha(newLabel);
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(newFicha.getImagen()).getImage().getScaledInstance(70, 70, Image.SCALE_DEFAULT));
            newFicha.getLabelFicha().setIcon((imageIcon));
            System.out.println(newFicha.getLabelFicha().getIcon());
            newFicha.getLabelFicha().setVisible(true);
            listaFichas.add(newFicha);
            FileManager.writeObject(listaFichas, "src/Partida/listafichas.dat");
            try {
                this.getRefCliente().getHiloCliente().getWriter().writeInt(6);
            } catch (IOException ex) {
                Logger.getLogger(InterfazCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.getLblFichaJugador().setIcon(imageIcon);
        }
        
        else if (seleccion.equals("Mewtwo")){
            
            Ficha newFicha = new Ficha("Mewtwo", "src/Imagenes/mewtwo.png", this.getLblNombreJugador().getText());
            this.getRefCliente().getHiloCliente().setFicha(newFicha);
            JLabel newLabel = new JLabel("");
            newLabel.setVisible(true);
            //this.getLblGo().add(newLabel);
            newFicha.setLabelFicha(newLabel);
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(newFicha.getImagen()).getImage().getScaledInstance(70, 70, Image.SCALE_DEFAULT));
            newFicha.getLabelFicha().setIcon((imageIcon));
            System.out.println(newFicha.getLabelFicha().getIcon());
            newFicha.getLabelFicha().setVisible(true);
            listaFichas.add(newFicha);
            FileManager.writeObject(listaFichas, "src/Partida/listafichas.dat");
            try {
                this.getRefCliente().getHiloCliente().getWriter().writeInt(6);
            } catch (IOException ex) {
                Logger.getLogger(InterfazCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.getLblFichaJugador().setIcon(imageIcon);
        }
        
        else if (seleccion.equals("Espeon")){
            
            Ficha newFicha = new Ficha("Espeon", "src/Imagenes/espeon.png", this.getLblNombreJugador().getText());
            this.getRefCliente().getHiloCliente().setFicha(newFicha);
            JLabel newLabel = new JLabel("");
            newLabel.setVisible(true);
            //this.getLblGo().add(newLabel);
            newFicha.setLabelFicha(newLabel);
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(newFicha.getImagen()).getImage().getScaledInstance(70, 70, Image.SCALE_DEFAULT));
            newFicha.getLabelFicha().setIcon((imageIcon));
            System.out.println(newFicha.getLabelFicha().getIcon());
            newFicha.getLabelFicha().setVisible(true);
            listaFichas.add(newFicha);
            FileManager.writeObject(listaFichas, "src/Partida/listafichas.dat");
            try {
                this.getRefCliente().getHiloCliente().getWriter().writeInt(6);
            } catch (IOException ex) {
                Logger.getLogger(InterfazCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.getLblFichaJugador().setIcon(imageIcon);
        }
        
        else if (seleccion.equals("Ditto")){
            
            Ficha newFicha = new Ficha("Ditto", "src/Imagenes/ditto.png", this.getLblNombreJugador().getText());
            this.getRefCliente().getHiloCliente().setFicha(newFicha);
            JLabel newLabel = new JLabel("");
            newLabel.setVisible(true);
            //this.getLblGo().add(newLabel);
            newFicha.setLabelFicha(newLabel);
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(newFicha.getImagen()).getImage().getScaledInstance(70, 70, Image.SCALE_DEFAULT));
            newFicha.getLabelFicha().setIcon((imageIcon));
            System.out.println(newFicha.getLabelFicha().getIcon());
            newFicha.getLabelFicha().setVisible(true);
            listaFichas.add(newFicha);
            FileManager.writeObject(listaFichas, "src/Partida/listafichas.dat");
            try {
                this.getRefCliente().getHiloCliente().getWriter().writeInt(6);
            } catch (IOException ex) {
                Logger.getLogger(InterfazCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.getLblFichaJugador().setIcon(imageIcon);
        }
        
        else if (seleccion.equals("Cyndaquil")){
            
            Ficha newFicha = new Ficha("Cyndaquil", "src/Imagenes/cyndaquil.png", this.getLblNombreJugador().getText());
            this.getRefCliente().getHiloCliente().setFicha(newFicha);
            JLabel newLabel = new JLabel("");
            newLabel.setVisible(true);
            //this.getLblGo().add(newLabel);
            newFicha.setLabelFicha(newLabel);
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(newFicha.getImagen()).getImage().getScaledInstance(70, 70, Image.SCALE_DEFAULT));
            newFicha.getLabelFicha().setIcon((imageIcon));
            System.out.println(newFicha.getLabelFicha().getIcon());
            newFicha.getLabelFicha().setVisible(true);
            listaFichas.add(newFicha);
            FileManager.writeObject(listaFichas, "src/Partida/listafichas.dat");
            try {
                this.getRefCliente().getHiloCliente().getWriter().writeInt(6);
            } catch (IOException ex) {
                Logger.getLogger(InterfazCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.getLblFichaJugador().setIcon(imageIcon);
        }
        
        else if (seleccion.equals("Totodile")){
            
            Ficha newFicha = new Ficha("Totodile", "src/Imagenes/totodile.png", this.getLblNombreJugador().getText());
            this.getRefCliente().getHiloCliente().setFicha(newFicha);
            JLabel newLabel = new JLabel("");
            newLabel.setVisible(true);
            //this.getLblGo().add(newLabel);
            newFicha.setLabelFicha(newLabel);
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(newFicha.getImagen()).getImage().getScaledInstance(70, 70, Image.SCALE_DEFAULT));
            newFicha.getLabelFicha().setIcon((imageIcon));
            System.out.println(newFicha.getLabelFicha().getIcon());
            newFicha.getLabelFicha().setVisible(true);
            listaFichas.add(newFicha);
            FileManager.writeObject(listaFichas, "src/Partida/listafichas.dat");
            try {
                this.getRefCliente().getHiloCliente().getWriter().writeInt(6);
            } catch (IOException ex) {
                Logger.getLogger(InterfazCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.getLblFichaJugador().setIcon(imageIcon);
        }
    }//GEN-LAST:event_btnSeleccionFichaActionPerformed

    private void btnEndTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndTurnActionPerformed
        // TODO add your handling code here:
        try {
                this.getRefCliente().getHiloCliente().writer.writeInt(9);
                this.getRefCliente().getHiloCliente().writer.writeUTF(this.getLblNombreJugador().getText());
            } catch (IOException ex) {
                Logger.getLogger(InterfazCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_btnEndTurnActionPerformed

    public JLabel getLblStatusPartida() {
        return lblStatusPartida;
    }

    public void setLblStatusPartida(JLabel lblStatusPartida) {
        this.lblStatusPartida = lblStatusPartida;
    }

    public JComboBox<String> getCbSeleccion() {
        return cbSeleccion;
    }

    public void setCbSeleccion(JComboBox<String> cbSeleccion) {
        this.cbSeleccion = cbSeleccion;
    }

    public JLabel getLblTurno() {
        return lblTurno;
    }

    public void setLblTurno(JLabel lblTurno) {
        this.lblTurno = lblTurno;
    }

    public JLabel getLblUsuarioLanzamiento() {
        return lblUsuarioLanzamiento;
    }

    public void setLblUsuarioLanzamiento(JLabel lblUsuarioLanzamiento) {
        this.lblUsuarioLanzamiento = lblUsuarioLanzamiento;
    }

    public JTextArea getTxaHistorial() {
        return txaHistorial;
    }

    public void setTxaHistorial(JTextArea txaHistorial) {
        this.txaHistorial = txaHistorial;
    }

    public JTextArea getTxaMensajes() {
        return txaMensajes;
    }

    public void setTxaMensajes(JTextArea txaMensajes) {
        this.txaMensajes = txaMensajes;
    }

    public JTextField getTxfMensaje() {
        return txfMensaje;
    }

    public void setTxfMensaje(JTextField txfMensaje) {
        this.txfMensaje = txfMensaje;
    }

    public JLabel getLblNumDinero() {
        return lblNumDinero;
    }

    public void setLblNumDinero(JLabel lblNumDinero) {
        this.lblNumDinero = lblNumDinero;
    }
    
    public void setFinalPartida(){
        this.lblStatusPartida.setText("Partida terminada");
    }

    
    public void setInicioPartida(){             // Configura la partida con los datos iniciales para empezarla
        lblStatusPartida.setText("Partida Iniciada");
        lblNumDinero.setText("Dinero: $" + refCliente.getHiloCliente().getDinero());
      //  lblNumCasas.setText("Numero de casas: " + refCliente.getHiloCliente().getNumCasas());
     //   lblNumHoteles.setText("Numero de hoteles: " + refCliente.getHiloCliente().getNumHoteles());
     //   lblNumPropiedades.setText("Numero de propiedades: " + refCliente.getHiloCliente().getNumPropiedades());
    }
    
    public void seleccionFicha(){
        
        //infoBox("Por favor escoja la ficha que desesa.","Selección de ficha");
        SeleccionFicha cbFicha = new SeleccionFicha(this);
        cbFicha.pack();
        cbFicha.setTitle("Por favor seleccione su ficha, " + nombreJugador);
        cbFicha.setVisible(true);
    }
    
    public void pintarLanzamientoDados (int valor1, int valor2, String usuario){    // Para escribir en la interfaz del cliente los valores de los dice rolls    
        
      //  lblDado1.setText(valor1 + "");
     //   lblDado2.setText(valor2 + "");
      //  lblDado1.setBackground(Color.red);
      //  lblDado2.setBackground(Color.red);
        
        if (!btnLanzarDados.isEnabled())
            btnLanzarDados.setEnabled(true);
        
        lblUsuarioLanzamiento.setText(usuario);
    }
    
    
    public void pintarTurno(String turno){              // Para escribir en la interfaz del cliente el jugador que está jugando actualmente
        this.nombreTurno = turno;
        lblTurno.setText(turno);
    }
    
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompraCasa;
    private javax.swing.JButton btnCompraHotel;
    private javax.swing.JButton btnComprarPropActual;
    private javax.swing.JButton btnEndTurn;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnHipotecar;
    private javax.swing.JButton btnLanzarDados;
    private javax.swing.JButton btnSeleccionFicha;
    private javax.swing.JButton btnVenderEdificio;
    private javax.swing.JButton btnVenderProp;
    private javax.swing.JComboBox<String> cbEdificios;
    private javax.swing.JComboBox<String> cbPropiedades;
    private javax.swing.JComboBox<String> cbSeleccion;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel109;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel110;
    private javax.swing.JPanel jPanel113;
    private javax.swing.JPanel jPanel116;
    private javax.swing.JPanel jPanel118;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel70;
    private javax.swing.JPanel jPanel72;
    private javax.swing.JPanel jPanel77;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblAdministrar;
    private javax.swing.JLabel lblChat;
    private javax.swing.JLabel lblDado1;
    private javax.swing.JLabel lblDado2;
    private javax.swing.JLabel lblDinero;
    private javax.swing.JPanel lblElMuelle;
    private javax.swing.JPanel lblElMuelle1;
    private javax.swing.JPanel lblElMuelle10;
    private javax.swing.JPanel lblElMuelle11;
    private javax.swing.JPanel lblElMuelle12;
    private javax.swing.JPanel lblElMuelle13;
    private javax.swing.JPanel lblElMuelle14;
    private javax.swing.JPanel lblElMuelle15;
    private javax.swing.JPanel lblElMuelle16;
    private javax.swing.JPanel lblElMuelle17;
    private javax.swing.JPanel lblElMuelle18;
    private javax.swing.JPanel lblElMuelle19;
    private javax.swing.JPanel lblElMuelle2;
    private javax.swing.JPanel lblElMuelle20;
    private javax.swing.JPanel lblElMuelle21;
    private javax.swing.JPanel lblElMuelle22;
    private javax.swing.JPanel lblElMuelle23;
    private javax.swing.JPanel lblElMuelle24;
    private javax.swing.JPanel lblElMuelle25;
    private javax.swing.JPanel lblElMuelle26;
    private javax.swing.JPanel lblElMuelle27;
    private javax.swing.JPanel lblElMuelle28;
    private javax.swing.JPanel lblElMuelle29;
    private javax.swing.JPanel lblElMuelle3;
    private javax.swing.JPanel lblElMuelle30;
    private javax.swing.JPanel lblElMuelle32;
    private javax.swing.JPanel lblElMuelle33;
    private javax.swing.JPanel lblElMuelle34;
    private javax.swing.JPanel lblElMuelle35;
    private javax.swing.JPanel lblElMuelle36;
    private javax.swing.JPanel lblElMuelle37;
    private javax.swing.JPanel lblElMuelle38;
    private javax.swing.JPanel lblElMuelle4;
    private javax.swing.JPanel lblElMuelle5;
    private javax.swing.JPanel lblElMuelle7;
    private javax.swing.JPanel lblElMuelle8;
    private javax.swing.JPanel lblElMuelle9;
    private javax.swing.JLabel lblFicha;
    private javax.swing.JLabel lblFichaJugador;
    private javax.swing.JPanel lblGo1;
    private javax.swing.JLabel lblHistorial;
    private javax.swing.JPanel lblImpuestos1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNombreJugador;
    private javax.swing.JLabel lblNumDinero;
    private javax.swing.JLabel lblSeleccionFicha;
    private javax.swing.JLabel lblStatusPartida;
    private javax.swing.JLabel lblTurno;
    private javax.swing.JLabel lblTurnoDe;
    private javax.swing.JLabel lblUsuarioLanzamiento;
    private javax.swing.JLabel lblVenderEdificio;
    private javax.swing.JPanel pnlFicha;
    private javax.swing.JPanel pnlTablero;
    private javax.swing.JPanel pnlToolbar;
    private javax.swing.JTextArea txaHistorial;
    private javax.swing.JTextArea txaMensajes;
    private javax.swing.JTextField txfMensaje;
    // End of variables declaration//GEN-END:variables
}
