/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente;

import Partida.FileManager;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import progra2.Progra2;

/**
 *
 * @author aleja
 */
public class SeleccionFicha extends javax.swing.JFrame {
    
    InterfazCliente refPantalla;
    /**
     * Creates new form SeleccionFicha
     */
    public SeleccionFicha(InterfazCliente refPantalla) {
        this.refPantalla = refPantalla;
        initComponents();
    }

    private SeleccionFicha() {
        
    }
    
    

    public InterfazCliente getRefPantalla() {
        return refPantalla;
    }

    public void setRefPantalla(InterfazCliente refPantalla) {
        this.refPantalla = refPantalla;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnListo = new javax.swing.JButton();
        cbSeleccion = new javax.swing.JComboBox<>();
        lblSeleccion = new javax.swing.JLabel();
        lblSeleccione = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnListo.setText("Listo");
        btnListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListoActionPerformed(evt);
            }
        });

        cbSeleccion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbSeleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chikorita", "Slowbro", "Charizard", "Pikachu", "Yamper", "Rayquaza", "Suicune", "Entei", "Raikoui", "Mewtwo", "Espeon", "Ditto", "Cyndaquil", "Totodile" }));

        lblSeleccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSeleccion.setText("Selección:");

        lblSeleccione.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSeleccione.setText("Seleccione su ficha!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSeleccion)
                        .addGap(18, 18, 18)
                        .addComponent(cbSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(lblSeleccione)))
                .addContainerGap(95, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnListo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSeleccione)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeleccion)
                    .addComponent(cbSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btnListo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListoActionPerformed
        // TODO add your handling code here:
        String seleccion = this.cbSeleccion.getSelectedItem().toString();
        System.out.println(seleccion);
        
        if (seleccion.equals("Chikorita")){
            
            Ficha newFicha = new Ficha("Chikorita", "src/Imagenes/chikorita.png", this.getRefPantalla().getLblNombreJugador().getText());
            this.getRefPantalla().getRefCliente().getHiloCliente().setFicha(newFicha);
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getNombre());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getNombreJugador());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getImagen());
            JLabel newLabel = new JLabel("");
            newLabel.setVisible(true);
           // this.getRefPantalla().getLblGo().add(newLabel);
            newFicha.setLabelFicha(newLabel);
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(newFicha.getImagen()).getImage().getScaledInstance(80, 80, Image.SCALE_DEFAULT));
            newFicha.getLabelFicha().setIcon((imageIcon));
            System.out.println(newFicha.getLabelFicha().getIcon());
            newFicha.getLabelFicha().setVisible(true);
            System.out.println(this.getRefPantalla().getPnlTablero().getLayout().getClass().getName());
            FileManager.writeObject(newFicha, "src/Partida/ficha" + newFicha.getNombre() + ".dat");
            
        }
        
        else if (seleccion.equals("Slowbro")){
            
            Ficha newFicha = new Ficha("Slowbro", "src/Imagenes/slowbro.png", this.getRefPantalla().getLblNombreJugador().getText());
            this.getRefPantalla().getRefCliente().getHiloCliente().setFicha(newFicha);
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getNombre());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getNombreJugador());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getImagen());
            JLabel newLabel = new JLabel("");
            newLabel.setVisible(true);
          //  this.getRefPantalla().getLblGo().add(newLabel);
            newFicha.setLabelFicha(newLabel);
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(newFicha.getImagen()).getImage().getScaledInstance(80, 80, Image.SCALE_DEFAULT));
            newFicha.getLabelFicha().setIcon((imageIcon));
            System.out.println(newFicha.getLabelFicha().getIcon());
            newFicha.getLabelFicha().setVisible(true);
            System.out.println(this.getRefPantalla().getPnlTablero().getLayout().getClass().getName());
            FileManager.writeObject(newFicha, "src/Partida/ficha" + newFicha.getNombre() + ".dat");
            
        }
        
        else if (seleccion.equals("Charizard")){
            
            Ficha newFicha = new Ficha("Charizard", "src/Imagenes/charizard.png", this.getRefPantalla().getLblNombreJugador().getText());
            this.getRefPantalla().getRefCliente().getHiloCliente().setFicha(newFicha);
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getNombre());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getNombreJugador());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getImagen());
            JLabel newLabel = new JLabel("");
            newLabel.setVisible(true);
           // this.getRefPantalla().getLblGo().add(newLabel);
            newFicha.setLabelFicha(newLabel);
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(newFicha.getImagen()).getImage().getScaledInstance(80, 80, Image.SCALE_DEFAULT));
            newFicha.getLabelFicha().setIcon((imageIcon));
            System.out.println(newFicha.getLabelFicha().getIcon());
            newFicha.getLabelFicha().setVisible(true);
            System.out.println(this.getRefPantalla().getPnlTablero().getLayout().getClass().getName());
            FileManager.writeObject(newFicha, "src/Partida/ficha" + newFicha.getNombre() + ".dat");
            
        }
        
        else if (seleccion.equals("Pikachu")){
            
            Ficha newFicha = new Ficha("Pikachu", "src/Imagenes/pikachu.png", this.getRefPantalla().getLblNombreJugador().getText());
            this.getRefPantalla().getRefCliente().getHiloCliente().setFicha(newFicha);
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getNombre());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getNombreJugador());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getImagen());
            JLabel newLabel = new JLabel("");
            newLabel.setVisible(true);
           // this.getRefPantalla().getLblGo().add(newLabel);
            newFicha.setLabelFicha(newLabel);
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(newFicha.getImagen()).getImage().getScaledInstance(80, 80, Image.SCALE_DEFAULT));
            newFicha.getLabelFicha().setIcon((imageIcon));
            System.out.println(newFicha.getLabelFicha().getIcon());
            newFicha.getLabelFicha().setVisible(true);
            System.out.println(this.getRefPantalla().getPnlTablero().getLayout().getClass().getName());
            FileManager.writeObject(newFicha, "src/Partida/ficha" + newFicha.getNombre() + ".dat");
            
        }
        
        else if (seleccion.equals("Yamper")){
            
            Ficha newFicha = new Ficha("Yamper", "src/Imagenes/yamper.png", this.getRefPantalla().getLblNombreJugador().getText());
            this.getRefPantalla().getRefCliente().getHiloCliente().setFicha(newFicha);
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getNombre());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getNombreJugador());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getImagen());
            JLabel newLabel = new JLabel("");
            newLabel.setVisible(true);
           // this.getRefPantalla().getLblGo().add(newLabel);
            newFicha.setLabelFicha(newLabel);
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(newFicha.getImagen()).getImage().getScaledInstance(80, 80, Image.SCALE_DEFAULT));
            newFicha.getLabelFicha().setIcon((imageIcon));
            System.out.println(newFicha.getLabelFicha().getIcon());
            newFicha.getLabelFicha().setVisible(true);
            System.out.println(this.getRefPantalla().getPnlTablero().getLayout().getClass().getName());
            FileManager.writeObject(newFicha, "src/Partida/ficha" + newFicha.getNombre() + ".dat");
            
        }
        
        else if (seleccion.equals("Rayquaza")){
            
            Ficha newFicha = new Ficha("Rayquaza", "src/Imagenes/rayquaza.png", this.getRefPantalla().getLblNombreJugador().getText());
            this.getRefPantalla().getRefCliente().getHiloCliente().setFicha(newFicha);
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getNombre());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getNombreJugador());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getImagen());
            JLabel newLabel = new JLabel("");
            newLabel.setVisible(true);
           // this.getRefPantalla().getLblGo().add(newLabel);
            newFicha.setLabelFicha(newLabel);
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(newFicha.getImagen()).getImage().getScaledInstance(80, 80, Image.SCALE_DEFAULT));
            newFicha.getLabelFicha().setIcon((imageIcon));
            System.out.println(newFicha.getLabelFicha().getIcon());
            newFicha.getLabelFicha().setVisible(true);
            System.out.println(this.getRefPantalla().getPnlTablero().getLayout().getClass().getName());
            FileManager.writeObject(newFicha, "src/Partida/ficha" + newFicha.getNombre() + ".dat");
            
        }
        
        else if (seleccion.equals("Suicune")){
            
            Ficha newFicha = new Ficha("Suicune", "src/Imagenes/suicune.png", this.getRefPantalla().getLblNombreJugador().getText());
            this.getRefPantalla().getRefCliente().getHiloCliente().setFicha(newFicha);
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getNombre());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getNombreJugador());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getImagen());
            JLabel newLabel = new JLabel("");
            newLabel.setVisible(true);
            //this.getRefPantalla().getLblGo().add(newLabel);
            newFicha.setLabelFicha(newLabel);
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(newFicha.getImagen()).getImage().getScaledInstance(80, 80, Image.SCALE_DEFAULT));
            newFicha.getLabelFicha().setIcon((imageIcon));
            System.out.println(newFicha.getLabelFicha().getIcon());
            newFicha.getLabelFicha().setVisible(true);
            System.out.println(this.getRefPantalla().getPnlTablero().getLayout().getClass().getName());
            FileManager.writeObject(newFicha, "src/Partida/ficha" + newFicha.getNombre() + ".dat");
            
        }
        
        else if (seleccion.equals("Entei")){
            
            Ficha newFicha = new Ficha("Entei", "src/Imagenes/entei.png", this.getRefPantalla().getLblNombreJugador().getText());
            this.getRefPantalla().getRefCliente().getHiloCliente().setFicha(newFicha);
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getNombre());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getNombreJugador());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getImagen());
            JLabel newLabel = new JLabel("");
            newLabel.setVisible(true);
           // this.getRefPantalla().getLblGo().add(newLabel);
            newFicha.setLabelFicha(newLabel);
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(newFicha.getImagen()).getImage().getScaledInstance(80, 80, Image.SCALE_DEFAULT));
            newFicha.getLabelFicha().setIcon((imageIcon));
            System.out.println(newFicha.getLabelFicha().getIcon());
            newFicha.getLabelFicha().setVisible(true);
            System.out.println(this.getRefPantalla().getPnlTablero().getLayout().getClass().getName());
            FileManager.writeObject(newFicha, "src/Partida/ficha" + newFicha.getNombre() + ".dat");
            
        }
        
        else if (seleccion.equals("Raikou")){
            
            Ficha newFicha = new Ficha("Raikou", "src/Imagenes/raikou.png", this.getRefPantalla().getLblNombreJugador().getText());
            this.getRefPantalla().getRefCliente().getHiloCliente().setFicha(newFicha);
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getNombre());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getNombreJugador());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getImagen());
            JLabel newLabel = new JLabel("");
            newLabel.setVisible(true);
            //this.getRefPantalla().getLblGo().add(newLabel);
            newFicha.setLabelFicha(newLabel);
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(newFicha.getImagen()).getImage().getScaledInstance(80, 80, Image.SCALE_DEFAULT));
            newFicha.getLabelFicha().setIcon((imageIcon));
            System.out.println(newFicha.getLabelFicha().getIcon());
            newFicha.getLabelFicha().setVisible(true);
            System.out.println(this.getRefPantalla().getPnlTablero().getLayout().getClass().getName());
            FileManager.writeObject(newFicha, "src/Partida/ficha" + newFicha.getNombre() + ".dat");
            
        }
        
        else if (seleccion.equals("Mewtwo")){
            
            Ficha newFicha = new Ficha("Mewtwo", "src/Imagenes/mewtwo.png", this.getRefPantalla().getLblNombreJugador().getText());
            this.getRefPantalla().getRefCliente().getHiloCliente().setFicha(newFicha);
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getNombre());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getNombreJugador());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getImagen());
            JLabel newLabel = new JLabel("");
            newLabel.setVisible(true);
            //this.getRefPantalla().getLblGo().add(newLabel);
            newFicha.setLabelFicha(newLabel);
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(newFicha.getImagen()).getImage().getScaledInstance(80, 80, Image.SCALE_DEFAULT));
            newFicha.getLabelFicha().setIcon((imageIcon));
            System.out.println(newFicha.getLabelFicha().getIcon());
            newFicha.getLabelFicha().setVisible(true);
            System.out.println(this.getRefPantalla().getPnlTablero().getLayout().getClass().getName());
            FileManager.writeObject(newFicha, "src/Partida/ficha" + newFicha.getNombre() + ".dat");
            
        }
        
        else if (seleccion.equals("Espeon")){
            
            Ficha newFicha = new Ficha("Espeon", "src/Imagenes/espeon.png", this.getRefPantalla().getLblNombreJugador().getText());
            this.getRefPantalla().getRefCliente().getHiloCliente().setFicha(newFicha);
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getNombre());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getNombreJugador());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getImagen());
            JLabel newLabel = new JLabel("");
            newLabel.setVisible(true);
            //this.getRefPantalla().getLblGo().add(newLabel);
            newFicha.setLabelFicha(newLabel);
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(newFicha.getImagen()).getImage().getScaledInstance(80, 80, Image.SCALE_DEFAULT));
            newFicha.getLabelFicha().setIcon((imageIcon));
            System.out.println(newFicha.getLabelFicha().getIcon());
            newFicha.getLabelFicha().setVisible(true);
            System.out.println(this.getRefPantalla().getPnlTablero().getLayout().getClass().getName());
            FileManager.writeObject(newFicha, "src/Partida/ficha" + newFicha.getNombre() + ".dat");
            
        }
        
        else if (seleccion.equals("Ditto")){
            
            Ficha newFicha = new Ficha("Ditto", "src/Imagenes/ditto.png", this.getRefPantalla().getLblNombreJugador().getText());
            this.getRefPantalla().getRefCliente().getHiloCliente().setFicha(newFicha);
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getNombre());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getNombreJugador());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getImagen());
            JLabel newLabel = new JLabel("");
            newLabel.setVisible(true);
            //this.getRefPantalla().getLblGo().add(newLabel);
            newFicha.setLabelFicha(newLabel);
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(newFicha.getImagen()).getImage().getScaledInstance(80, 80, Image.SCALE_DEFAULT));
            newFicha.getLabelFicha().setIcon((imageIcon));
            System.out.println(newFicha.getLabelFicha().getIcon());
            newFicha.getLabelFicha().setVisible(true);
            System.out.println(this.getRefPantalla().getPnlTablero().getLayout().getClass().getName());
            FileManager.writeObject(newFicha, "src/Partida/ficha" + newFicha.getNombre() + ".dat");
            
        }
        
        else if (seleccion.equals("Cyndaquil")){
            
            Ficha newFicha = new Ficha("Cyndaquil", "src/Imagenes/cyndaquil.png", this.getRefPantalla().getLblNombreJugador().getText());
            this.getRefPantalla().getRefCliente().getHiloCliente().setFicha(newFicha);
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getNombre());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getNombreJugador());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getImagen());
            JLabel newLabel = new JLabel("");
            newLabel.setVisible(true);
            //this.getRefPantalla().getLblGo().add(newLabel);
            newFicha.setLabelFicha(newLabel);
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(newFicha.getImagen()).getImage().getScaledInstance(80, 80, Image.SCALE_DEFAULT));
            newFicha.getLabelFicha().setIcon((imageIcon));
            System.out.println(newFicha.getLabelFicha().getIcon());
            newFicha.getLabelFicha().setVisible(true);
            System.out.println(this.getRefPantalla().getPnlTablero().getLayout().getClass().getName());
            FileManager.writeObject(newFicha, "src/Partida/ficha" + newFicha.getNombre() + ".dat");
            
        }
        
        else if (seleccion.equals("Totodile")){
            
            Ficha newFicha = new Ficha("Totodile", "src/Imagenes/totodile.png", this.getRefPantalla().getLblNombreJugador().getText());
            this.getRefPantalla().getRefCliente().getHiloCliente().setFicha(newFicha);
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getNombre());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getNombreJugador());
            System.out.println(this.getRefPantalla().getRefCliente().getHiloCliente().getFicha().getImagen());
            JLabel newLabel = new JLabel("");
            newLabel.setVisible(true);
            //this.getRefPantalla().getLblGo().add(newLabel);
            newFicha.setLabelFicha(newLabel);
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(newFicha.getImagen()).getImage().getScaledInstance(70, 70, Image.SCALE_DEFAULT));
            newFicha.getLabelFicha().setIcon((imageIcon));
            System.out.println(newFicha.getLabelFicha().getIcon());
            newFicha.getLabelFicha().setVisible(true);
            System.out.println(this.getRefPantalla().getPnlTablero().getLayout().getClass().getName());
            FileManager.writeObject(newFicha, "src/Partida/ficha" + newFicha.getNombre() + ".dat");
            
        }

        super.dispose();
    }//GEN-LAST:event_btnListoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new SeleccionFicha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListo;
    private javax.swing.JComboBox<String> cbSeleccion;
    private javax.swing.JLabel lblSeleccion;
    private javax.swing.JLabel lblSeleccione;
    // End of variables declaration//GEN-END:variables

    Object getCbSeleccion() {
        return cbSeleccion;
    }
    
    
}
